apiVersion: 
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-aio-max-operations
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /etc/sysctl.d/99-aio-max-nr.conf
        mode: 06444
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64;ZnMuYWlvLW1heC1uciA9IDEwNg1NzYK
